TP3-I = TP3-IFT2425-I
TP3-II = TP3-IFT2425-II
TP3-III = TP3-IFT2425-III

all: 1 2 3

1:
	./compilegcc ${TP3-I}
	./${TP3-I}

2:
	./compilegcc ${TP3-II}
	./${TP3-II}

3:
	./compilegcc ${TP3-III}
	./${TP3-III}
